<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [2]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv("../data/data.csv")

# Display the first few rows
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,0,0,0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,2,2,2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,3,3,3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,4,4,4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [3]:
# df.to_csv("data.csv")

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [4]:
# Write your code here
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65457 entries, 0 to 65456
Columns: 117 entries, Unnamed: 0.2 to JobSat
dtypes: float64(13), int64(4), str(100)
memory usage: 197.2 MB

In [5]:
i = 0
for col in df.columns:
	if i < 10:
		i += 1
		print(col, "--->", df[col].dtype, "-->", df[col].isna().sum())

Unnamed: 0.2 ---> int64 --> 0
Unnamed: 0.1 ---> int64 --> 0
Unnamed: 0 ---> int64 --> 0
ResponseId ---> int64 --> 0
MainBranch ---> str --> 0
Age ---> str --> 0
Employment ---> str --> 0
RemoteWork ---> str --> 10637
Check ---> str --> 0
CodingActivities ---> str --> 10977

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [6]:
# Write your code here
df.describe()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65457.000000,65457.000000,65457.000000,65457.000000,3.374400e+04,29664.000000,29330.000000,29399.000000,29417.000000,29456.000000,29454.000000,29462.000000,29462.000000,29456.000000,29451.000000,2.343700e+04,29131.000000
mean,32728.000000,32728.000000,32728.000000,32714.493591,2.963490e+145,11.466323,18.578998,7.520604,10.059485,24.339971,22.964277,20.279127,16.167837,10.953481,9.953618,8.615893e+04,6.934915
std,18895.952622,18895.952622,18895.952622,18892.431636,5.443794e+147,9.168205,25.965347,18.421094,21.831924,27.088870,27.017634,26.110706,24.844177,22.904463,21.775070,1.867532e+05,2.088356
min,0.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16364.000000,16364.000000,16364.000000,16354.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32728.000000,32728.000000,32728.000000,32716.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.000000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49092.000000,49092.000000,49092.000000,49076.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.000000,25.000000,20.000000,10.000000,10.000000,1.080000e+05,8.000000
max,65456.000000,65456.000000,65456.000000,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [7]:
df.Country = df.Country.replace({"Viet nam" : "Vietnam"})

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [8]:
## Write your code here
df = pd.get_dummies(df, columns=["Employment"], dtype=str, prefix="Employment")
df.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,ResponseId,MainBranch,Age,RemoteWork,Check,CodingActivities,EdLevel,...,"Employment_Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time","Employment_Student, full-time;Not employed, but looking for work;Retired","Employment_Student, full-time;Not employed, but looking for work;Student, part-time","Employment_Student, full-time;Retired","Employment_Student, full-time;Student, part-time","Employment_Student, full-time;Student, part-time;Employed, part-time","Employment_Student, full-time;Student, part-time;Retired","Employment_Student, part-time","Employment_Student, part-time;Employed, part-time","Employment_Student, part-time;Retired"
0,0,0,0,1,I am a developer by profession,Under 18 years old,Remote,Apples,Hobby,Primary/elementary school,...,False,False,False,False,False,False,False,False,False,False
1,1,1,1,2,I am a developer by profession,35-44 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",...,False,False,False,False,False,False,False,False,False,False
2,2,2,2,3,I am a developer by profession,45-54 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",...,False,False,False,False,False,False,False,False,False,False
3,3,3,3,4,I am learning to code,18-24 years old,NaN,Apples,NaN,Some college/university study without earning ...,...,False,False,False,False,False,False,False,False,False,False
4,4,4,4,5,I am a developer by profession,18-24 years old,NaN,Apples,NaN,"Secondary school (e.g. American high school, G...",...,False,False,False,False,False,False,False,False,False,False

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [9]:
## Write your code here
df.isna().sum(axis=0).sort_values(ascending=False)

AINextMuch less integrated                                                                                                                               64309
AINextLess integrated                                                                                                                                    63102
AINextNo change                                                                                                                                          52955
AINextMuch more integrated                                                                                                                               52018
EmbeddedAdmired                                                                                                                                          48718
                                                                                                                                                         ...
Employment_Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired                            0
Employment_Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired        0
Employment_Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                0
Employment_Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                                   0
Employment_Student, part-time;Retired                                                                                                                        0
Length: 226, dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [10]:
## Write your code here
df = df.fillna({"ConvertedCompYearly": df.ConvertedCompYearly.median(), "RemoteWork" : df.RemoteWork.mode()[0]})

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [11]:
## Write your code here
# ABOVE

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [12]:
## Write your code here
min = df.ConvertedCompYearly.min()
max = df.ConvertedCompYearly.max()
df["ConvertedCompYearly_MinMax"] = (df.ConvertedCompYearly - min) / (max - min)
df["ConvertedCompYearly_MinMax"]

0        0.003998
1        0.003998
2        0.003998
3        0.003998
4        0.003998
           ...
65452    0.003998
65453    0.003998
65454    0.000061
65455    0.003998
65456    0.003998
Name: ConvertedCompYearly_MinMax, Length: 65457, dtype: float64

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [13]:
## Write your code here
import math, numpy
df["ConvertedCompYearly_log"] = numpy.log1p(df.ConvertedCompYearly)
df["ConvertedCompYearly_log"]

0        11.082158
1        11.082158
2        11.082158
3        11.082158
4        11.082158
           ...
65452    11.082158
65453    11.082158
65454     6.905753
65455    11.082158
65456    11.082158
Name: ConvertedCompYearly_log, Length: 65457, dtype: float64

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [14]:
## Write your code here
df.YearsCodePro.value_counts()
df.YearsCodePro = df.YearsCodePro.replace({"More than 50 years": 50, "Less than 1 year": 1})
df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'], errors='coerce')
df.YearsCodePro = df.YearsCodePro.astype("Int64")

bins = numpy.linspace(start=df.YearsCodePro.min(), stop=df.YearsCodePro.max(), num=5)
df["ExperienceLevel"] = pd.cut(x=df.YearsCodePro, bins=bins, labels=["junior", "knowledgable", "experienced", "pro"])
df.ExperienceLevel

0                 NaN
1        knowledgable
2         experienced
3                 NaN
4                 NaN
             ...
65452          junior
65453          junior
65454          junior
65455          junior
65456             pro
Name: ExperienceLevel, Length: 65457, dtype: category
Categories (4, str): ['junior' < 'knowledgable' < 'experienced' < 'pro']

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.